services:
  - type: web
    name: school-crm-backend
    runtime: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_URL
        fromDatabase:
          name: school-crm-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: https://school-crm-frontend-gamma.vercel.app
    region: oregon

  - type: postgresql
    name: school-crm-db
    plan: free
    region: oregon
