services:
  - type: web
    name: school-crm-backend
    runtime: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_STORAGE
        value: /tmp/database.sqlite
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: https://school-crm-frontend-gamma.vercel.app
